In [56]:
# from inside a Python REPL

import numpy as np
np.__version__

'1.23.5'

In [57]:
np_arr = np.array(range(100), dtype=int).reshape(10, 10)
np_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
np_arr + 1  # adds 1 to every cell (element), but np_arr itself is unchanged

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [59]:
np_arr*2

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198]])

In [60]:
type(np_arr)

numpy.ndarray

In [61]:
py_arr = np_arr.tolist() # extract an ordinary Python list

type(py_arr)

list

In [62]:
np_arr.ndim    # how many dimensions? 

2

In [63]:
np_arr.shape # how many elements along each axis?

(10, 10)

In [64]:
np_arr[2:5, 7:]

array([[27, 28, 29],
       [37, 38, 39],
       [47, 48, 49]])

In [65]:
try:
    py_arr[2:5, 7:]
except:
    print("Sorry, not an option")

Sorry, not an option


In [66]:
np_arr[3:8, 6:]

array([[36, 37, 38, 39],
       [46, 47, 48, 49],
       [56, 57, 58, 59],
       [66, 67, 68, 69],
       [76, 77, 78, 79]])

In [67]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5] 

In [68]:
# a * b  # gives "TypeError: can't multiply sequence by non-int of type 'list'"

In [69]:
try:
    a * b
except:
    print("Sorry, not an option")

Sorry, not an option


In [70]:
arr0 = np.array([1, 2, 3, 4], dtype=int)
print("arr0 =", arr0)

arr1 = np.array([5, 6, 7, 8], dtype=int)
print("arr1 =", arr1)

# ordinary Python lists will not do this
print("arr0 + arr1 =", arr0 + arr1)
print("arr0 * arr1 =", arr0 * arr1)

arr0 = [1 2 3 4]
arr1 = [5 6 7 8]
arr0 + arr1 = [ 6  8 10 12]
arr0 * arr1 = [ 5 12 21 32]


In [71]:
In ordinary Python, the syntax is a lot busier (more complex):

SyntaxError: invalid syntax (1392976666.py, line 1)

In [ ]:
arr0 = [1, 2, 3, 4]
print("arr0 =", arr0)

arr1 = [5, 6, 7, 8]
print("arr1 =", arr1)

# using list comprehension syntax instead
print("arr0 + arr1 =", [i + j for i, j in zip(arr0, arr1)])
print("arr0 * arr1 =", [i * j for i, j in zip(arr0, arr1)])

In [ ]:
my_list = [3, "three", True, 6.0, (1, 2, 3), {"1": 1, "2": 2}]

for i in range(len(my_list)):
    print(f"data: {my_list[i]} : type : {type(my_list[i])}")

In [ ]:
my_list_array = np.array([1, 2, 3, 4])

print(my_list_array)
my_list_array.dtype

In [ ]:
my_list_array = np.array([1, 2, 3, 4.4])

print(my_list_array)
my_list_array.dtype

In [ ]:
my_list_array = np.array([1, 2, 3, 4.4, "Mathew"])

print(my_list_array)
my_list_array.dtype

In [ ]:
from array import array  # Array can be handled in Python by a module named array.

py_array = array('i', range(20))
py_array

In [ ]:
# Python arrays, like Python lists, like strings, concatenate when added

py_array + py_array

In [ ]:
We still CANNOT do elementwise operations with Python's array type:

In [ ]:
# py_array * py_array  # TypeError: can't multiply sequence by non-int of type 'array.array'

In [ ]:
try:
    py_array * py_array
except:
    print("Operation undefined")

In [ ]:
multi_type = np.array(['str', 3, 5.0, ["L", "I", "S", "T"]], dtype=object)
multi_type

In [ ]:
print(type(multi_type[1]))  # individual elements preserve their type
print(type(multi_type[3]))

In [ ]:
multi_type.itemsize # itemsize returns the size (in bytes) of each element of a NumPy array

In [ ]:
multi_type.size  # size is the total number of elements in the ndarray. It is equal to the product of elements of the shape.

In [ ]:
multi_type.shape

In [ ]:
len(multi_type) # same as size

In [ ]:
multi_type.nbytes # size times itemsize. Total bytes consumed by the elements of the array.

In [ ]:
my_list = [1, 2, 3]
my_list

In [ ]:
my_array = np.array(my_list)
my_array

In [ ]:
np.array([1, 2, 3])

In [ ]:
my_list = [[1, 2, 3, 4], [1, 2, 3, 4], [2, 3, 4, 5], [2, 3, 4, 5]]  # a nested list
my_list 

In [ ]:
my_array = np.array(my_list)  # We created a multidimensional (2D) array using nested list
my_array

In [ ]:
my_array @ my_array # matrix multiplication, a linear algebra operation

In [ ]:
my_list =[[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]], [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]]
my_list  # another nested list 

In [ ]:
my_array = np.array(my_list)  # We created a multidimensional (3D) array using nested list
my_array

In [ ]:
# What about Tuples

np.array((1, 2, 3, 4))

In [ ]:
np.array(((1, 2, 3, 4), (1, 2, 3, 4)))

In [ ]:
np.arange(10)

In [ ]:
np.arange(0, 10)

In [ ]:
np.arange(0, 11, 2)  # Creates a sequence of numbers (array) from 0 (inclusive) to 11 (exclusive), increasing by 2 by 2.

In [ ]:
np.arange(0, 31, 3)

In [ ]:
range(0, 10, 2)

In [ ]:
for i in range(0, 10, 2):
    print(i)

In [ ]:
mylist = []

for i in range(0, 10, 2):
    mylist.append(i)

print(mylist)
print(mylist[0])

In [ ]:
list(range(0, 10, 2))

In [ ]:
np.arange(0, 11, 5)

In [ ]:
np.linspace(0, 10, 50)

In [ ]:
# This is the same as the previous one. Because keyword parameter "num"=50 is default

np.linspace(0, 10)

In [ ]:
np.linspace(0, 10, 51)

In [ ]:
np.linspace(0, 10, 51, dtype="int") 

# When we set the dtype parameter to "int" it took the integer part of the numbers

In [ ]:
np.linspace(0, 100, 51, dtype="int")

In [ ]:
set(np.linspace(0, 10, 51, dtype="int"))

In [ ]:
np.linspace(0, 10, 5, axis=0)

In [ ]:
np.linspace(0, [10, 20], 5, axis=0)

In [ ]:
np.linspace(0, [10, 20], 5, axis=0)

In [ ]:
np.linspace([0, 10] ,[10, 20], 5, axis=0)

In [ ]:
np.linspace([0, 10], [10, 20], 5, axis=1)

In [ ]:
np.zeros(3)

In [ ]:
np.zeros(10, dtype=int)

In [ ]:
np.zeros((5, 5))

In [ ]:
np.zeros((4, 4), dtype=str)

In [ ]:
np.zeros((4, 4), dtype=bool)

In [ ]:
np.ones(3)

In [ ]:
np.ones((3, 3))

In [ ]:
np.ones((3, 5), dtype=int)

In [ ]:
np.ones((4, 4), dtype=str)

In [ ]:
np.ones((4, 4), dtype=bool)

In [ ]:
np.full((3, 5), 3)

In [ ]:
np.full((3, 5), "3")

In [ ]:
np.full((3, 3), "steve")

In [ ]:
np.full((2, 4, 3), 255) # [depth, height(row), width(column)] # RGB code:255 (color:RedGreenBlue code)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
a = np.full((2, 4, 3), 255) # [depth, height(row), width(column)]

a[:, :, 0] = 255 # red
a[:, :, 1] = 0 # green
a[:, :, 2] = 0 # blue

a

In [ ]:
**It created an array of 2 containing 4 rows and 3 columns.**

In [ ]:
plt.imshow(a);  # [height, width, depth/channels]

In [ ]:
However, for any image that is 2 rows, 4 columns and 3 depth/channels dimensions. That is, the last dimension is the "depth/channel".

In [ ]:
a = np.full((2, 4, 3), 255) # [depth, height(row), width(column)]

a[:, :, 0] = 0 # red
a[:, :, 1] = 255 # green
a[:, :, 2] = 0 # blue

a

In [ ]:
plt.imshow(a);  # [height, width, depth/channels]

In [ ]:
fig, ax = plt.subplots(figsize=(5, 5))   # ax is for axes  

ax.xaxis.set_visible(False)             # turn off x tick marks and labels
ax.yaxis.set_visible(False)             # turn off y tick marks and labels
plt.imshow(a);                          # [height, width, depth/channels]

In [ ]:
ident = np.eye(4)
ident

In [ ]:
ident.diagonal()

In [ ]:
**It created a two-dimensional square array with 1 in its diagonal. Its other name is identity matrix.**

In [ ]:
np.eye(4, dtype=int)

In [ ]:
np.eye(4, dtype=bool)

In [ ]:
rand_int = np.random.randint(0, 10, (4, 4))
rand_int

In [ ]:
rand_int @ ident  # matrix multiply by identity matrix: A * I == A

In [ ]:
np.random.rand(2)

In [ ]:
**It generated a one-dimensional array containing 2 values in a uniform distribution between 0-1.**

**Normal distribution: mean = median (the distribution where the mean equals the median.)**

In [ ]:
np.random.rand(5, 5)

In [ ]:
normalized = np.random.randn(5, 5)
normalized

# np.round(normalized, 3)

In [ ]:
sample_data = np.random.randn(5555)

plt.hist(sample_data, bins=30)
plt.show();

In [ ]:
**The larger the number of elements in the produced array, the more standard normal distribution it will be.<br>
So, mean will be close to 0, std will be close to 1 and its graph will be as above.**

In [ ]:
import seaborn as sns

sns.histplot(sample_data, bins=30, kde=True);

In [ ]:
# the standard normal distribution gives a mean of approximately 0

sample_data.mean()  

In [ ]:
# the standard normal distribution gives a variance of approximately 1

sample_data.std()**2 

In [ ]:
np.random.randint(10)

In [ ]:
np.random.randint(1, 100)

In [ ]:
**It has produced a single value between 1-100 and returns the result as an int.**

In [ ]:
# [low, high)

np.random.randint(1, 100, 10)

In [ ]:
np.random.randint(10, size=10)  # the only int (10) refers to the high (stop)

In [ ]:
**Generates 10 elements randomly from numbers up to 10.<br>
If the min value is not specified, size (size=10) should be specified like this.**

In [ ]:
np.random.randint(5, size=(2, 4))

In [ ]:
**It has generated a two-dimensional array of 2*4, containing randomly generated values from numbers 0 (inclusive) to 5 (exclusive).**

In [ ]:
np.random.randint(5, 25, size=(2, 4))

In [ ]:
**It has generated a two-dimensional array of 2*4, containing randomly generated values from numbers 5 (inclusive) to 25 (exclusive).**

In [ ]:
np.random.randint(1, [3, 50, 100])  # 3 different upper bounds

In [ ]:
np.random.randint(1, [3, 50])  # each upper bounds represents each columns

In [ ]:
np.random.randint(1, [3, 50, 100], size=(5, 3)) 

# 3 different upper bounds with 5x3 matrix

# each columns fit to upper bound in order of the values which in a list.[3, 50, 100]

In [ ]:
**Since there are 3 elements in the list of values, there should be 3 columns. Otherwise, it will throw an error.**

In [ ]:
np.random.randint([1, 30, 70], 111)  # 3 different lower bounds

In [ ]:
np.random.randint([1, 30, 70], [10, 40, 80], size=(4,3))  # 3 different upper and lower bounds

In [73]:
arr = np.arange(36)
rand_arr = np.random.randint(0, 50, 10)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
rand_arr

In [ ]:
# The shape atribute is used to see the shape of an array.

arr.shape

In [ ]:
arr.reshape(1, 36)

In [ ]:
**If we want to add dimension without changing the shape of the array, this method, adding the value of 1 at the beginning, should be used.**

In [ ]:
arr.reshape(36, 1)

In [ ]:
arr.reshape(6, 6)

In [ ]:
**We have converted the shape of the array to a 2 dimensional array of 6*6. While doing this process, attention should be paid to the number (size) of elements of the array.**

In [ ]:
arr.reshape(4, 9)  # We converted it to a 2D array in the form of 4*9.

In [ ]:
arr.reshape(4, -1)  # Sets the number of columns relative to the number of rows.
                    # Here the number of rows is important for us 

In [76]:
arr.reshape(-3, 4)  # Sets the number of rows relative to the number of columns.
                    # Here the number of columns is important for us 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [81]:
arr.reshape(1, 4, 9)  # We have increased the dimension of a 4*9 array.

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]]])

In [119]:
arr.reshape(3, 4, 3)  # We have created a 3D 4*3 array 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [82]:
arr.reshape(6,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

In [120]:
rand_arr

array([45, 48, 19, 30, 23, 44,  3,  1, 15, 28])

In [121]:
rand_arr.max()  # to find the max value of array. 

48

In [122]:
rand_arr.argmax()  # to find the index of max value in the array. 

1

In [123]:
rand_arr.min()  # to find the min value of array. 

1

In [124]:
rand_arr.argmin()  # to find the index of min value in the array.

7

In [125]:
rand_arr.reshape(2, 5)

array([[45, 48, 19, 30, 23],
       [44,  3,  1, 15, 28]])

In [126]:
rand_arr

array([45, 48, 19, 30, 23, 44,  3,  1, 15, 28])

In [ ]:
**reshape does not change the shape of the original array.<br>
To make the change permanent, you must assign it to a new variable.**

In [127]:
rand_arr_new = rand_arr.reshape(2, 5)
rand_arr_new

array([[45, 48, 19, 30, 23],
       [44,  3,  1, 15, 28]])

In [128]:
rand_arr_new.argmin()

7

In [129]:
rand_arr_new.argmax()

1

In [130]:
# Vector

arr.shape  # shape is a tuple of integers representing the size of the ndarray in each dimension.

(36,)

In [131]:
# Notice the two sets of brackets

arr.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [132]:
arr.shape

(36,)

In [133]:
a = arr.reshape(6, 6)
a.shape

(6, 6)

In [134]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [135]:
arr.dtype  # To look at the data type of the elements of an array

# dtype tells the data type of the elements of a NumPy array. In NumPy array, all the elements have the same data type.

dtype('int32')

In [136]:
type(arr)  # to look at the data type of an array

numpy.ndarray

In [137]:
type(arr[1])  # to find the type of the 1st element of the array

numpy.int32

In [138]:
b = np.full((4, 6), 2.2)
b

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [139]:
b.dtype

dtype('float64')

In [140]:
# rows and columns = 2 dimensions

arr.ndim  # ndim represents the number of dimensions (axes) of the ndarray.

1

In [141]:
arr.shape

(36,)

In [142]:
b.ndim

2

In [143]:
b.shape

(4, 6)

In [144]:
arr.size  # To look at the total number of elements in an array

# size is the total number of elements in the ndarray. It is equal to the product of elements of the shape

36

In [145]:
len(arr)

36

In [ ]:
**If the array is one-dimensional, the number of elements of the array can also be found with the len() function.**

In [146]:
b = np.random.randint(10, size=(3, 5))

# We have created a random array of 3 by 5 (3*5) from the numbers up to 10 (exclusive)

In [147]:
b

array([[4, 2, 9, 5, 5],
       [9, 0, 9, 1, 7],
       [0, 2, 7, 9, 2]])

In [148]:
b.ndim  # ndim attribute returns the number of dimensions of an array

2

In [149]:
b.shape  # returns a tuple with each index having the number of corresponding elements.

(3, 5)

In [150]:
b.size  # This attribute calculates the total number of elements present in the NumPy array.

15

In [151]:
len(b)  # If the array is two-dimensional, the len() function returns the number of rows.

3

In [152]:
b.itemsize  # itemsize returns the size (in bytes) of each element of a NumPy array. here is 4 bytes

4