In [11]:
import numpy as np
import pandas as pd


# import warnings
# warnings.filterwarnings("ignore")  # to suppress all warnings

In [12]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

In [13]:
np.concatenate([x, y])  # concatenates two or more one-dimensional arrays.

array([1, 2, 3, 4, 5, 6])

In [14]:
np.concatenate([x, y, z], axis=0)  # The default axis value is 0. That is, in single dimensions, it combines along axis=0.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# np.concatenate([x, y, z], axis=1) # gives an error

In [16]:
print(x.reshape(1, 3).shape)

np.concatenate([x.reshape(1, 3), y.reshape(1, 3), z.reshape(1, 3)], axis=0)

# This is how it works if the arrays are reshaped by reshape() method.

(1, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# The second approach

np.concatenate([[x, y, z]], axis=0)
               
# By changing the number of square brackets for a one-dimensional array; 
# However, BE NOTED THAT we can combine along with only axis=0.               

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# The third approach

np.concatenate([x, y, z], axis=0).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# The fourth approach

print(x.shape)
print(x.reshape(1, 3).shape)
print(x.reshape(-1, 1).shape)

np.concatenate((x.reshape(-1, 1), y.reshape(-1, 1), z.reshape(-1, 1)), axis=1)

(3,)
(1, 3)
(3, 1)


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

You can also use **``stack()``** to join sequence of arrays. Just make sure both the 1D arrays are of the same shape.

In [20]:
# The fifth approach

print(x.shape)
print(y.shape)

np.stack([x, y]).reshape(-1)

(3,)
(3,)


array([1, 2, 3, 4, 5, 6])

**``hstack()``** method Stack arrays in sequence horizontally, So if two 1D arrays are given then it flatten it to a single 1D

In [21]:
# The sixth approach

np.hstack([x, y])

array([1, 2, 3, 4, 5, 6])

In [13]:
a = np.random.randint(10, size=(2, 3))
b = np.random.randint(10, size=(2, 3))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [14]:
a, b

(array([[8, 9, 5],
        [0, 4, 5]]),
 array([[7, 3, 5],
        [8, 0, 6]]))

In [15]:
# Combining two arrays of 2*3 on the basis of axis=0 results in an array of 4*3.

np.concatenate([a, b])

<IPython.core.display.Javascript object>

array([[8, 9, 5],
       [0, 4, 5],
       [7, 3, 5],
       [8, 0, 6]])

In [16]:
# Combining two arrays of 2*3 on the basis of axis=1 results in an array of 2*6.

np.concatenate([a, b], axis=1)

<IPython.core.display.Javascript object>

array([[8, 9, 5, 7, 3, 5],
       [0, 4, 5, 8, 0, 6]])

In [17]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

print(x.shape)
print(y.shape)

x, y

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(2, 3)
(3, 3)


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]))

In [18]:
# For example: When combining on the basis of axis=0, if the column numbers are equal, 
# it does the combination and does not give an error.

np.concatenate([x, y], axis=0)

<IPython.core.display.Javascript object>

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [20]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x

<IPython.core.display.Javascript object>

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [21]:
# With the np.split() method, you can split an array into parts as you specify.

np.split(x, [3, 5])  # divided into 0:3, 3:5, 5:

<IPython.core.display.Javascript object>

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[3, 5]`` would, for ``axis=0``, result in
- ``ary[:3]``
- ``ary[3:5]``
- ``ary[5:]``

In [22]:
# We assigned the parts we divided as 0:3, 3:5, 5: to a new variable.

a, b, c = np.split(x, [3, 5])

<IPython.core.display.Javascript object>

In [23]:
a

array([1, 2, 3])

In [24]:
b

array([99, 99])

In [25]:
c

array([3, 2, 1])

In [26]:
np.split(x, [4])  # It divided the array into two parts as 0:4, 4:  

<IPython.core.display.Javascript object>

[array([ 1,  2,  3, 99]), array([99,  3,  2,  1])]

In [27]:
np.split(x, 4)

# If we do not give the index number in square brackets, it will divide it into 4 equal parts.
# However, in this case, the number of elements in the array must be a number divisible by 4.

<IPython.core.display.Javascript object>

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

In [28]:
# x = np.array([1, 2, 3, 99, 99, 3, 2, 1, 4])  # the length of array is 9
# np.split(x, 4)

# # ValueError: array split does not result in an equal division

In [29]:
m = np.arange(20).reshape(5, 4)
m

<IPython.core.display.Javascript object>

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
np.split(m, 5, axis=0)  # axis=0 ==> we divided it into 5 equal parts along the rows. 

<IPython.core.display.Javascript object>

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [31]:
# When splitting two-dimensional arrays, the axis must be specified along with the indexes.

np.split(m, [1, 3], axis=0)  # axis=0 ==> we divided it into three parts as :1, 1:3:, 3:, along the rows.

<IPython.core.display.Javascript object>

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [32]:
np.split(m, [1, 3], axis=1)  # axis=1 ==> we divided it into three parts, :1, 1:3:, 3:, along the columns.

<IPython.core.display.Javascript object>

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [33]:
np.vsplit(m, [1, 3])  # With vertical split, we divided it into two parts as :3, 3: along the lines (like axis=0).

<IPython.core.display.Javascript object>

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [34]:
upper, lower = np.vsplit(m, [3])

<IPython.core.display.Javascript object>

In [35]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
# Focus on double square brackets. All rows are still 2d-arrays.

np.vsplit(m, 5)

<IPython.core.display.Javascript object>

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [38]:
np.hsplit(m, [2])  # With horizontal split, we divided it into two parts as :3, 3: along the columns (like axis=1).

<IPython.core.display.Javascript object>

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [39]:
left, right = np.hsplit(m, [2])

<IPython.core.display.Javascript object>

In [40]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [41]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [42]:
v = np.array([2, 1, 4, 3, 5])
v

<IPython.core.display.Javascript object>

array([2, 1, 4, 3, 5])

In [43]:
np.sort(v)  # Returns a sorted array but does not change the original one.

<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5])

In [44]:
v

array([2, 1, 4, 3, 5])

In [45]:
v.sort()  # changed inplace

# when used in this way, it makes this change both in the sequence (order) and in the original one.

In [46]:
v

array([1, 2, 3, 4, 5])

In [47]:
twoD = np.random.randint(5, 100, (3, 3))
twoD

<IPython.core.display.Javascript object>

array([[50, 48, 36],
       [22, 61, 62],
       [32, 79,  6]])

In [48]:
np.sort(twoD, axis=0)  # the rows are sorted from upper to lower and column by column

<IPython.core.display.Javascript object>

array([[22, 48,  6],
       [32, 61, 36],
       [50, 79, 62]])

In [49]:
np.sort(twoD, axis=1)  # the columns are sorted from left to right and row by row

<IPython.core.display.Javascript object>

array([[36, 48, 50],
       [22, 61, 62],
       [ 6, 32, 79]])

In [50]:
#Creating sample array

arr = np.arange(0, 11)

<IPython.core.display.Javascript object>

In [51]:
#Show

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
#Get a value at an index

arr[8]

8

In [53]:
# Negative indexing works like in python lists

arr[-1]

10

In [54]:
# Get values in a range

arr[1:5]  # Returns the elements in the index of 1 (inclusive)-5 (exclusive)

array([1, 2, 3, 4])

In [55]:
# Get values in a range

arr[:5]

array([0, 1, 2, 3, 4])

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
# arr[start:stop:step], odds

arr[1::2]

array([1, 3, 5, 7, 9])

In [58]:
# arr[start:stop:step], evens

arr[0::2]

# Returns the elements of the array corresponding to the even indexes starting from 0 with a step interval of 2

array([ 0,  2,  4,  6,  8, 10])

In [59]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

#Show
arr_2d

<IPython.core.display.Javascript object>

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
#Indexing row

arr_2d[1]

array([20, 25, 30])

In [61]:
# Format is arr_2d[row][col] or arr_2d[row, col]

# Getting individual element value

arr_2d[1][2]

30

In [62]:
# Getting individual element value

arr_2d[1, 2]

30

In [63]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
# 2D array slicing
print(arr_2d)

# Shape (2, 2) from top right corner
arr_2d[0:2, 1:]

# Returns the rows from the beginning to the second index and the columns from the 1st to the end.

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([[10, 15],
       [25, 30]])

In [65]:
# Shape bottom row

arr_2d[2]  # Returns the elements in the 2nd index of row

array([35, 40, 45])

In [66]:
#Shape bottom row

arr_2d[2, :]  # Returns the row at the index of 2 with all columns

array([35, 40, 45])

In [67]:
# Middle column

arr_2d[:, 1]  # Returns the column at the index of 1 with all rows

array([10, 25, 40])

In [68]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
# The very right column

arr_2d[:, 2]

# When slicing two-dimensional arrays, first row and then column ranges should be written.

array([15, 30, 45])

In [70]:
# let's convert 25 to 55

arr_2d[1, 1] = 99
arr_2d

# In this way, we can permanently replace the values at the index we defined with another value.

array([[ 5, 10, 15],
       [20, 99, 30],
       [35, 40, 45]])

In [71]:
# default dtype is int. take a look at the assigning of the float value

arr_2d[1][1] = 7.7
arr_2d

# When you assign a float value, it converts to int because the default value of the array is int.

array([[ 5, 10, 15],
       [20,  7, 30],
       [35, 40, 45]])

#### v = np.arange(0, 30, 3)
v

In [73]:
v[1]

3

In [74]:
v[3]

9

In [75]:
v[7]

21

In [76]:
# we can select separate elements using their indices in a list

index_list=[1, 3, 7]

v[index_list]

array([ 3,  9, 21])

In [77]:
# Fancy indexing is used to select multiple values at different indices at the same time.

v[[1 ,3, 7]]  # Returns the values in index of 1, 3 and 5 in a one-dimensional array.

array([ 3,  9, 21])

In [78]:
# Set up matrix

arr2d = np.zeros((10, 10), dtype=int)
arr2d

<IPython.core.display.Javascript object>

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [79]:
arr2d.shape

(10, 10)

In [80]:
# Length of array

length_arr = arr2d.shape[0]
length_arr

10

In [81]:
arr2d[0]  # Returns the 1st row of the array named arr2d

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr2d[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
#Set up array

for i in range(length_arr):
    arr2d[i]=i
    
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [84]:
arr2d[3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

Fancy indexing allows the following

In [85]:
# we can select separate rows by indices in a list

arr2d[[2, 4, 6, 8]]  # Returns the 2nd, 4th, 6th, and 8th rows of the array named arr2d in the order we defined.

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [86]:
# Allows in any order

arr2d[[6, 4, 2, 7]]  # Returns the 6th, 4th, 2nd, and 7th rows of the array named arr2d in the any order we defined.

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [87]:
jj = np.arange(1, 17).reshape(4, 4)

<IPython.core.display.Javascript object>

In [88]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [89]:
# let's select separate values of 5 and 12
# row 1 and column 0. row 2 and column 3. 

jj[[1, 2], [0, 3]]

array([ 5, 12])

In [90]:
# this time let's select separate values of 1, 10 and 16

jj[[0, 2, 3], [0, 1, 3]]  # the element 0 of row index 0, element 1 of row index 2, element 3 of row index 3

array([ 1, 10, 16])

In [91]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
# let's select 6 and 8 which are in the same row (index 1)

jj[1, [1, 3]]

array([6, 8])

In [93]:
# let's select 2 and 14 which are the same column (index 1)

jj[[0, 3], 1]

array([ 2, 14])

In [94]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [95]:
# let's select two middle columns

jj[:, [1, 2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [96]:
jj[1, [1, 3]]  # 1st element of row index 1, 3rd element of row index 1

array([6, 8])

In [97]:
# let's select center small square (4 elements)

jj[1:3, [1, 2]]

array([[ 6,  7],
       [10, 11]])

In [98]:
# remember, how normal slicing is executed

jj[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [99]:
arr = np.arange(1, 11)
arr

<IPython.core.display.Javascript object>

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [101]:
bool_arr = arr > 4

In [102]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [103]:
# When we write a condition in [] and write the name of the array next to it, 
# we get an array containing the elements that meet this condition.

arr[arr < 6]

array([1, 2, 3, 4, 5])

In [104]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
# Sometimes it may be necessary to apply more than one condition.

(arr != 3) & (arr != 4)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [106]:
# and ==> &

arr[(arr != 3) & (arr != 4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [107]:
# if you want you can use if_statement and for_loop

con_arr = []

for i in arr:
    if (i != 3) & (i != 4):
        con_arr.append(i)
print(con_arr)    

[1, 2, 5, 6, 7, 8, 9, 10]


In [108]:
# Let us remember our arr

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
#Setting a value with index range (Broadcasting)
arr[:5] = 77

#Show
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [110]:
# What about broadcating on a Python list

a = [0, 2, 4, 6, 8, 10]
a

[0, 2, 4, 6, 8, 10]

In [111]:
# a[0:3] = 100 # gives an error of "TypeError: can only assign an iterable"

In [112]:
a[:3] = [100, 100, 100]

In [113]:
a

[100, 100, 100, 6, 8, 10]

In [114]:
# Let us reset our array, we'll see why we had to reset in  a moment
arr = np.arange(0, 11)

# Show
arr

<IPython.core.display.Javascript object>

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
# Important notes on Slices
slice_of_arr = arr[0:6]

# Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [116]:
#Change Slice
slice_of_arr[:] = 99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [117]:
arr  # The changes I copied from the array and made to the array also change the original array.

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [118]:
#To get a copy, need to be explicit

arr_copy = arr.copy()
arr_copy

# If you make a copy of the array and operate on its copy, the changes you made in the original array will not take place.

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [119]:
# We can assign a list of values in an exact dimension

arr_copy[:6] = [0, 1, 2, 3, 4, 5]

In [120]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [122]:
import numpy as np

arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [124]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [125]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [126]:
import warnings
warnings.filterwarnings('ignore')

In [127]:
# Warning on division by zero, but not an error!
# Just replaced with nan

arr / arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [128]:
# Also warning, but not an error instead infinity

1 / arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [129]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [130]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [131]:
v - 2

array([-1,  0,  1,  2,  3])

In [132]:
v * 10

array([10, 20, 30, 40, 50])

In [133]:
v*5 / 10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [134]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
#Taking Square Roots

# arr**0.5

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [136]:
#Calcualting exponential (e^)

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [137]:
# same as arr.max()

np.max(arr)

9

In [138]:
# there are many trigonometric functions

np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [139]:
np.sin(np.pi/2)

1.0

In [140]:
np.tan(np.pi/4)

0.9999999999999999

In [141]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [142]:
np.log10(1000)

3.0

In [143]:
v

array([1, 2, 3, 4, 5])

In [144]:
# v - 1

np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [145]:
x1=np.arange(9.0).reshape(3, 3)
x2=np.arange(3.0)

In [146]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [147]:
x2

array([0., 1., 2.])

In [148]:
# x1 - x2

np.subtract(x1, x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [149]:
# v + 2

np.add(v, 2)

array([3, 4, 5, 6, 7])

In [150]:
# v / 2

np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [151]:
np.multiply(v, 4)

array([ 4,  8, 12, 16, 20])

In [152]:
# v**2

np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [153]:
# v % 2

np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [154]:
np.absolute(np.array([-9]))

array([9])

In [155]:
v = np.array([1, 1, 2, 2, 3, 3, 3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [156]:
np.ptp(v)  # The name of the function comes from the acronym for ‘peak to peak’. 
           # It's the range of values (maximum - minimum) along an axis.

# The term of Peak-to-peak is used in Electrical Engineering, and
# Peak-to-peak value is the maximum voltage change occurring during one cycle of alternating voltage or current.

2

In [157]:
print(np.mean(v))

v.mean()

2.142857142857143


2.142857142857143

In [158]:
print(np.median(v))

np.percentile(v, 50)

# v.median()  # This gives an error of "AttributeError: 'numpy.ndarray' object has no attribute 'median'"

2.0


2.0

In [159]:
from scipy import stats

stats.mode(v)

# np.mode(v)  # AttributeError: module 'numpy' has no attribute 'mode'

ModeResult(mode=array([3]), count=array([3]))

In [160]:
v.std()

0.8329931278350429

In [161]:
v.var()

0.6938775510204082

In [162]:
v.sum()

15

In [163]:
v.min()  # Returns min values along axis=0

1

In [164]:
np.random.seed(42)  # When you want to work with randomly generated values in individual or team work, 
                    # seed() method is used to reach the same values.

xarr = np.random.randn(3, 3)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [165]:
np.corrcoef(xarr)

array([[ 1.        ,  0.33500663, -0.29669929],
       [ 0.33500663,  1.        ,  0.80039247],
       [-0.29669929,  0.80039247,  1.        ]])