In [2]:
import pandas as pd
import numpy as np

# import warnings
# warnings.filterwarnings("ignore")  # to suppress all warnings

In [3]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

In [4]:
pd.Series(labels)  # Here, we have created a Series from a list named "label" containing values of string.

0    a
1    b
2    c
dtype: object

In [5]:
pd.Series(my_list)  # Here, we have created a Series from a list named "my_list" containing values of interger.

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series([10, 20, 30])  # Here, we have created a Series from a list by directly putting inside the method.

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series([10, 20, "30"])

0    10
1    20
2    30
dtype: object

In [8]:
arr

array([10, 20, 30])

In [9]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int32

In [10]:
labels

['a', 'b', 'c']

In [11]:
pd.Series(data=arr, index=labels)  # You can create a Series from a numpy ndarray. We can change its index as well.

a    10
b    20
c    30
dtype: int32

In [12]:
d

{'a': 10, 'b': 20, 'c': 30}

In [13]:
pd.Series(d)  # If you have a dictionary, you can turn it into a series.

a    10
b    20
c    30
dtype: int64

It used the dictionary keys as index. The keys of the dictionary match with the Index values; hence, the default Index values have no effect.

In [14]:
pd.Series(data=d, index=['q', 'c', 'y'])

q     NaN
c    30.0
y     NaN
dtype: float64

In [15]:
pd.Series(data="Steve")

0    Steve
dtype: object

In [16]:
pd.Series(data="Steve", index=range(3))

# In order to create a Series from scalar value, an index must be provided. 
# The scalar value will be repeated to match the length of the index. 

0    Steve
1    Steve
2    Steve
dtype: object

In [17]:
pd.Series(data=10, index=['a', 'b', 'c'])

a    10
b    10
c    10
dtype: int64

In [18]:
# Let us first remember how a Numpy array looks like:
# While a value in a Numpy array does have invisible index (number location) which can be accessed by indexing, 
# a Series can have axis labels which can be indexed by a label.

np.arange(1, 17).reshape(4, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
pd.Series(np.arange(1, 17))

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
dtype: int32

In [20]:
# You can create a Series by set, list, and dict functions, and then use each one for its intended purpose.

objects = pd.Series([set, list, dict])
objects

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [21]:
print(objects[0])  # 0th element of the series we created above is <class 'set'>
objects[0]([2, 5, 7, 5, 8, 2])

# pd.Series(set)[0]([2, 5, 7, 5, 8, 2])

<class 'set'>


{2, 5, 7, 8}

In [22]:
objects[1](range(9)) 

# Since the first element of the Series is a list, when range(9) is put into it, 
# it creates a list of numbers between 0-9.

[0, 1, 2, 3, 4, 5, 6, 7, 8]

**A pandas Series can even hold functions (although unlikely that you will use this)**

In [23]:
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [24]:
pd.Series([sum, print, len])[1]("a")

# Since the second element is the print() function, it prints the we wrote next to it.

a


In [25]:
pd.Series([sum, print, len])[2]("clarusway")

# Since the second element is the len() function, we can find the length of the data we wrote next to it.

9

In [26]:
mix_data = ['Aziz', 2, True]

# Pandas Series is capable of holding data of any type (integer, string, float, python objects, etc.). 

In [27]:
ser = pd.Series(mix_data)
ser

0    Aziz
1       2
2    True
dtype: object

**While dtype of the Series above is "O" where 'O' is for "object"; On the otherhand, if you check the type of the individual elements of your Series, they are different. Each element of Series will keep its original dtype.**

In [28]:
ser.dtype  # Since object(Python string) is the most comprehensive one it returns the dtype of Series as an object.

dtype('O')

In [29]:
type(ser)  # When we look at the type of the Series, we see that it is the Pandas Series.

pandas.core.series.Series

In [30]:
type(ser[0])  # When we look at the type of the 0th element of the Series, we can see that it is str.

str

In [31]:
type(ser[1])  # When we look at the type of the 1st element of the Series, we can see that it is int.

int

In [32]:
# Let us remember NumPy dtypes

print(mix_data)
arr = np.array(mix_data)
arr

['Aziz', 2, True]


array(['Aziz', '2', 'True'], dtype='<U11')

In [33]:
# Let's check the type of third element in the array which was "boolean" in the list. 

type(arr[2])

numpy.str_

In [34]:
ser = pd.Series(np.random.randint(0, 100, 7))
ser

0    42
1    96
2     1
3    51
4    47
5    47
6    94
dtype: int32

In [35]:
type(ser)

pandas.core.series.Series

In [36]:
ser.dtype

dtype('int32')

In [37]:
# Pandas Series.shape attribute returns a tuple of the shape of the underlying data for the given series objects.

ser.shape  

(7,)

In [38]:
# Pandas Series.shape attribute returns the number of elements in the underlying data.

ser.size

7

In [39]:
len(ser)

7

In [40]:
# Pandas Series.shape attribute returns the number of dimensions of the underlying data, by definition it is 1 for series objects.

ser.ndim

1

In [41]:
ser

0    42
1    96
2     1
3    51
4    47
5    47
6    94
dtype: int32

In [42]:
# Pandas Series.index attribute is used to get or set the index labels of the given Series object.

ser.index

RangeIndex(start=0, stop=7, step=1)

In [43]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [44]:
# Pandas Series.keys() function is an alias for index. It returns the index labels of the given Series object.

ser.keys()

RangeIndex(start=0, stop=7, step=1)

In [45]:
for i in ser.index: # we can also use "keys()"
    print(i)

0
1
2
3
4
5
6


In [46]:
# Pandas Series.values attribute returns a Series containing values as ndarray or ndarray-like depending on the dtype.

ser.values

array([42, 96,  1, 51, 47, 47, 94])

In [47]:
# If we want to extract values to a list, rather than an array, we can create a list comprehension.

[i for i in ser.values]

[42, 96, 1, 51, 47, 47, 94]

In [48]:
for i in ser.values:
    print(i)

42
96
1
51
47
47
94


In [49]:
ser.items

# Why does the output look like messy?

<bound method Series.items of 0    42
1    96
2     1
3    51
4    47
5    47
6    94
dtype: int32>

In [50]:
# Pandas Series.items() function iterates over the given series object. 
# The function iterates over the tuples containing the index labels and corresponding value in the Series.

ser.items()

In [51]:
list(ser.items())

[(0, 42), (1, 96), (2, 1), (3, 51), (4, 47), (5, 47), (6, 94)]

In [52]:
for index, value in ser.items():
    print(f"Index : {index}, Value : {value}")

Index : 0, Value : 42
Index : 1, Value : 96
Index : 2, Value : 1
Index : 3, Value : 51
Index : 4, Value : 47
Index : 5, Value : 47
Index : 6, Value : 94


In [53]:
ser = pd.Series(data=np.random.randint(0, 25, 10), index=[i for i in "cbaefdgihj"])

In [54]:
ser

c    12
b    17
a     6
e     9
f    12
d    21
g     3
i    15
h    17
j    18
dtype: int32

In [55]:
# pandas.Series.head() function returns the first n rows for the object based on position. 
# It is useful for quickly testing if your object has the right type of data in it.
# For negative values of n, this function returns all rows except the last n rows, equivalent to df[:-n].

ser.head(3)

c    12
b    17
a     6
dtype: int32

In [56]:
# pandas.Series.tail() function returns last n rows from the object based on position. 
# It is useful for quickly verifying data, for example, after sorting or appending rows.
# For negative values of n, this function returns all rows except the first n rows, equivalent to df[n:].

ser.tail(2)

h    17
j    18
dtype: int32

In [57]:
# pandas.Series.sample() function returns a random sample of items from an axis of object.

ser.sample(2)

f    12
a     6
dtype: int32

In [58]:
# pandas.Series.sort_index() function sorts Series by index labels. 
# It returns a new Series sorted by label if inplace argument is False, otherwise updates the original series and returns None.

ser.sort_index(ascending=True)

a     6
b    17
c    12
d    21
e     9
f    12
g     3
h    17
i    15
j    18
dtype: int32

In [59]:
# pandas.Series.sort_values() function sorts the values in a Series by index labels in ascending or descending order by some criterion.

ser.sort_values(ascending=False)

d    21
j    18
b    17
h    17
i    15
c    12
f    12
e     9
a     6
g     3
dtype: int32

In [60]:
ser

c    12
b    17
a     6
e     9
f    12
d    21
g     3
i    15
h    17
j    18
dtype: int32

In [61]:
# pandas.Series.isin() function searches whether elements in Series are contained in values.
# It returns a boolean Series showing if each element in the Series matches an element in the passed sequence of values exactly.

ser.isin([5, 9])

c    False
b    False
a    False
e     True
f    False
d    False
g    False
i    False
h    False
j    False
dtype: bool

In [62]:
ser1 = pd.Series([1, 2, 3, 4], index = ['USA', 'Germany','RF', 'Japan'])
ser2 = pd.Series([1, 2, 5, 4, 6], index = ['USA', 'Germany','Italy', 'Japan', 'Spain'])

In [63]:
ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

In [64]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
Spain      6
dtype: int64

In [65]:
# Pandas Series.sort_index() function is used to sort the index labels of the given Series object.

ser1.sort_index()

Germany    2
Japan      4
RF         3
USA        1
dtype: int64

In [66]:
# Pandas Series.sort_values() function is used to sort the given series object in ascending or descending order by some criterion.

ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
Spain      6
dtype: int64

In [67]:
# Let's remember our "ser1":

ser1

USA        1
Germany    2
RF         3
Japan      4
dtype: int64

In [68]:
ser1[3]  # This basic indexing returned the value of 4 at the index number 3.

4

In [69]:
ser1.index[3]  # However, index attribute returned the label at the index number 3, so we saw which label is at that index.

'Japan'

In [70]:
# Pandas index.get_loc() function returns integer location, slice or boolean mask for requested label that lets you filter DataFrames based on conditions. 

ser1.index.get_loc('Japan') 

3

In [71]:
ser1['Japan']

4

In [72]:
ser1.Japan

4

In [73]:
print("The value at the 'Japan' index label:", ser1['Japan'])

The value at the 'Japan' index label: 4


In [74]:
print("The value at the index number 3:", ser1[3])

The value at the index number 3: 4


In [75]:
# ser1[4]  # IndexError: index 4 is out of bounds for axis 0 with size 4

In [76]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
Spain      6
dtype: int64

In [77]:
ser2[0]

1

In [78]:
ser2[2:]

Italy    5
Japan    4
Spain    6
dtype: int64

In [79]:
ser2[::-1]

Spain      6
Japan      4
Italy      5
Germany    2
USA        1
dtype: int64

In [80]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
RF         NaN
Spain      NaN
USA        2.0
dtype: float64

In [81]:
ser1 * ser2

Germany     4.0
Italy       NaN
Japan      16.0
RF          NaN
Spain       NaN
USA         1.0
dtype: float64

In [82]:
ser = pd.Series(data=[121, 200, 150, 99], index=["terry", "micheal", "orion", "jason"])
ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [83]:
ser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [84]:
ser['terry']

121

In [85]:
ser[0]

121

In [86]:
ser[[0, 2]]

terry    121
orion    150
dtype: int64

In [87]:
ser[["terry", "orion"]]

terry    121
orion    150
dtype: int64

In [88]:
ser[0:3]  # Be noted that when index number is used the last index number becomes EXCLUSIVE.  

terry      121
micheal    200
orion      150
dtype: int64

In [89]:
ser['terry':'orion']  # Be noted that when label index is used the last label index becomes INCLUSIVE.

terry      121
micheal    200
orion      150
dtype: int64

In [90]:
ser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [91]:
'terry' in ser

True

In [92]:
'bob' in ser

False

In [93]:
121 in ser.values

True

In [94]:
55 in ser.values

False

In [95]:
ser < 100

terry      False
micheal    False
orion      False
jason       True
dtype: bool

In [96]:
ser[ser < 100] = 100
ser

terry      121
micheal    200
orion      150
jason      100
dtype: int64

In [97]:
ser.isin([121])

# TypeError: only list-like objects are allowed to be passed to isin(), you passed a [int]

terry       True
micheal    False
orion      False
jason      False
dtype: bool

In [98]:
ser[ser.isin([121])] = 125
ser

terry      125
micheal    200
orion      150
jason      100
dtype: int64

In [99]:
# Let us remember first our array of "ser"

ser

terry      125
micheal    200
orion      150
jason      100
dtype: int64

In [100]:
ser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [101]:
ser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [102]:
ser.values

array([125, 200, 150, 100], dtype=int64)

In [103]:
ser.items

<bound method Series.items of terry      125
micheal    200
orion      150
jason      100
dtype: int64>

In [104]:
ser.items()

In [105]:
list(ser.items())

[('terry', 125), ('micheal', 200), ('orion', 150), ('jason', 100)]

In [106]:
for index, value in ser.items():
    print(index, value)

terry 125
micheal 200
orion 150
jason 100


In [107]:
ser

terry      125
micheal    200
orion      150
jason      100
dtype: int64

In [112]:
ser.sort_index(ascending=False)

terry      125
orion      150
micheal    200
jason      100
dtype: int64

In [109]:
ser.sort_values(ascending=False)

micheal    200
orion      150
terry      125
jason      100
dtype: int64